export const FETCH_AVAILABLE_PUPPIES = 'FETCH_AVAILABLE_PUPPIES';
export const FETCH_AVAILABLE_BREEDS = 'FETCH_AVAILABLE_BREEDS';

export const CHANGE_PET_TYPE = 'CHANGE_PET_TYPE';
export const CHANGE_PET_LOCATION = 'CHANGE_PET_LOCATION';
export const CHANGE_PET_BREED = 'CHANGE_PET_BREED';
export const CHANGE_PET_GENDER = 'CHANGE_PET_GENDER';

export const FETCH_PET_DETAILS = 'FETCH_PET_DETAILS';
export const FETCH_PETKEY_BREED_DETAILS = 'FETCH_PETKEY_BREED_DETAILS';

export const FETCH_BREED_DETAILS = 'FETCH_BREED_DETAILS';

export const FETCH_BREEDS = 'FETCH_BREEDS';
export const CHANGE_BREED = 'CHANGE_BREED';

export const FETCH_FINANCING_CONTENT = 'FETCH_FINANCING_CONTENT';

export const REQUESTING_PET_INFORMATION = 'REQUESTING_PET_INFORMATION';
export const SET_PET_FORM_FEEDBACK = 'SET_PET_FORM_FEEDBACK';

export const REQUESTING_BREED_INFORMATION = 'REQUESTING_BREED_INFORMATION';
export const SET_BREED_FORM_FEEDBACK = 'SET_BREED_FORM_FEEDBACK';

export const REQUESTING_CONTACT_INFORMATION = 'REQUESTING_CONTACT_INFORMATION';
export const SET_CONTACT_FORM_FEEDBACK = 'SET_CONTACT_FORM_FEEDBACK';
